/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#f9f8ff",
        "primary": "#5c5e66",
        "surface-container-high": "#e3e9ec",
        "on-surface-variant": "#586064",
        "primary-dim": "#50525a",
        "error": "#9f403d",
        "error-dim": "#4e0309",
        "on-error-container": "#752121",
        "error-container": "#fe8983",
        "background": "#f8f9fa",
        "on-error": "#fff7f6",
        "on-primary-fixed-variant": "#5a5b63",
        "tertiary-container": "#e3dbfd",
        "inverse-surface": "#0c0f10",
        "surface-container": "#eaeff1",
        "secondary-container": "#dfe2f3",
        "on-tertiary": "#fcf7ff",
        "on-secondary-fixed": "#3b3f4c",
        "on-tertiary-fixed-variant": "#5c5672",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#abb3b7",
        "primary-fixed": "#e2e2ec",
        "tertiary-fixed": "#e3dbfd",
        "surface-variant": "#dbe4e7",
        "on-tertiary-fixed": "#3f3a54",
        "on-surface": "#2b3437",
        "outline": "#737c7f",
        "surface-container-highest": "#dbe4e7",
        "tertiary-fixed-dim": "#d5cdee",
        "tertiary-dim": "#554f6b",
        "tertiary": "#615b77",
        "surface": "#f8f9fa",
        "surface-container-low": "#f1f4f6",
        "primary-container": "#e2e2ec",
        "on-background": "#2b3437",
        "inverse-primary": "#dfdfe9",
        "surface-tint": "#5c5e66",
        "on-primary": "#f8f7ff",
        "on-secondary-container": "#4d515f",
        "secondary-fixed-dim": "#d1d4e5",
        "secondary-fixed": "#dfe2f3",
        "primary-fixed-dim": "#d3d4dd",
        "on-primary-container": "#505159",
        "on-secondary-fixed-variant": "#575b69",
        "surface-dim": "#d1dce0",
        "inverse-on-surface": "#9b9d9e",
        "on-tertiary-container": "#524c68",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed": "#3d3f47",
        "secondary": "#5b5f6d"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}